CREATE DATABASE prueba;
use prueba;
CREATE TABLE USUARIO(
ID_USUARIO INT UNSIGNED PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL UNIQUE,
FECHA_RENOVACION DATE NOT NULL,
MES_CADUCIDAD TINYINT(2) UNSIGNED ZEROFILL CHECK(MES_CADUCIDAD > 1 AND MES_CADUCIDAD <= 12),
ANHO_CADUCIDAD YEAR CHECK (ANHO_CADUCIDAD >= 2021),
GENERO ENUM("MASCULINO", "FEMENINO") NOT NULL,
TIPO_USUARIO ENUM("GRATIS","DE_PAGO") NOT NULL DEFAULT "GRATIS");

 